# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_rooms', to='common.Floor')),
            ],
        ),
    ]
