# Generated by Django 2.0.5 on 2019-07-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Free'), (1, 'Busy'), (2, 'N/A')], null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('working', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='machines', to='common.Floor')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of', models.CharField(choices=[('WM', 'WashingMachine'), ('DR', 'Dryer')], max_length=2)),
                ('name', models.CharField(max_length=125)),
                ('treshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='laundry_room.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='machines', to='laundry_room.Type'),
        ),
    ]
