# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosogepsch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
