# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosogepsch_app', '0003_remove_floor_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_type',
            new_name='type',
        ),
    ]
