# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosogepsch_app', '0004_auto_20161214_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='ip_addr',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_query_time',
        ),
        migrations.AddField(
            model_name='floor',
            name='ip_addr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='last_query_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
