# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanulosch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningroom',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_rooms', to='tanulosch_app.Floor'),
        ),
    ]
