# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('WM', 'WashingMachine'), ('DR', 'Dryer')], max_length=2)),
                ('ip_addr', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('last_query_time', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='washing_app.Floor')),
            ],
        ),
    ]
