# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washing_app', '0002_auto_20161107_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='alias',
        ),
    ]
