# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washing_app', '0005_auto_20170412_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status_code',
            field=models.IntegerField(blank=True, choices=[(0, 'Free'), (1, 'Busy'), (2, 'N/A')], null=True),
        ),
    ]
